const quotes = [
    "I love you mostest",
    "Whatever you're going through, you got this!",
    "You should call me or text me",
    "You're the love of my life",
    "You mean the world to me",
    "I love it when I see you laugh",
    "Cuddling you on the couch and wathcing netflix is one of my happy places",
    "Pura Vita + ____ is the new Daves. ___ will be updated when we decide",
    "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Remember this one? What did the fish say when it swam into a wall?",
    "Aren't you looking gorgeous today (you always do)",
    "I'm so rpoud of you and everything that you've accomplished",
    "IT'S TIME TO STANDDD",
    "If you're tired take a nap, otherwise come see me",
    "Send me a picture of this in exchange for one thing I love about you. It must include the date somewhere",
    "Somehow you know me better than I know myself",
    "I appreciate everything you've done for me",
    "Did I ever tell you that you taught me what love felt like",
    "I love it when we're walking together and you hold my arm",
    "I love our tradition of always saying \"Goodnight\" and \"I love you\" before hanging up calls",
    "I love our night time kisses routine when we're not in the same city for extended periods of time",
    "I love our sneaky elevator kisses",
    "I love your booty ;)",
    "I love your passion and determination for making the world a better place",
    "I love the way we communicate and grow together",
    "I love it when I spend the night and you make my toothbrush for me",
    "You're the most beautiful and hot girl in the world",
    "There's nobody I'd rather be with than you"
]
export default quotes;